using System.Collections;
using System.Collections.Generic;
using TMPro;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.UI;

//using UnityEditor;

public class Story : MonoBehaviour
{
    public Text mokuhyou;
    public int storykaunnto=0,serihuokuru=0,susumiseigyo;
    private serihu2 serihu2;
    private pasuwado pas;
    public Canvas main;
    public GameObject syuzinnkou;
    public Text siraberu; // ã‚­ãƒ£ãƒ³ãƒã‚¹å†…ã®Textã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®å‚ç…§
    public ITEM item;
    private move move;
    private erebeitaa e;
    private tatakai tatakai;

    private syujinnkou sy;//ãƒ†ã‚¹ãƒˆãƒ—ãƒ¬ã‚¤ç”¨ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼
    // Start is called before the first frame update
    private gamekirikae gamekirikae;
    private sound sound;
    private pasCanvas p;
    public string devele="start2.exe",text="k.txt";
    //Devilãƒ»ï½”ãƒ»REXã®ãƒ‘ã‚¹ã¨ã€ã‚»ãƒ¼ãƒ–ç”¨ã®ãƒ†ã‚­ã‚¹ãƒˆãƒ•ã‚©ãƒ«ãƒ€ã®ãƒ‘ã‚¹â†‘//rexgameã®ãƒ•ã‚¡ã‚¤ãƒ«ã§ã‚‚ãƒ‘ã‚¹æŒ‡å®šã—ã¦ã‚‹
    void Start()
    {
         serihu2= FindObjectOfType<serihu2>();
         pas= FindObjectOfType<pasuwado>();
         item=FindObjectOfType<ITEM>();
         move=FindObjectOfType<move>();
         sy=FindObjectOfType<syujinnkou>();
         e=FindObjectOfType<erebeitaa>();
         tatakai=FindObjectOfType<tatakai>();
         gamekirikae=FindObjectOfType<gamekirikae>();
         sound=FindObjectOfType<sound>();
         //storykaunnto=21;//ãƒ†ã‚¹ãƒˆãƒ—ãƒ¬ã‚¤ç”¨ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼
         //sy.i=0;//ãƒ†ã‚¹ãƒˆãƒ—ãƒ¬ã‚¤ç”¨ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼
         p=FindObjectOfType<pasCanvas>();
         
    }

    // Update is called once per frame
    void Update()
    {
        if(storykaunnto==1)mokuhyou.text ="ç›®æ¨™:å»ºç‰©ã®ä¸­ã«å…¥ã‚ã†";
        if(storykaunnto==3)mokuhyou.text ="ç›®æ¨™:éƒ¨å±‹ã‚’æ¢ç´¢ã—ã‚ˆã†";
        if(storykaunnto==5)mokuhyou.text ="ç›®æ¨™:éŸ³ãŒãªã£ãŸå ´æ‰€ã‚’æ¢ãã†";
        if(storykaunnto==7)mokuhyou.text ="ç›®æ¨™:ç™½ã„æŸµã‚’æ¢ãã†";
        if(storykaunnto==9)mokuhyou.text ="ç›®æ¨™:æ£®ç”°ã¨æˆ¦ã„ã«è¡Œã“ã†";
        if(storykaunnto==13)mokuhyou.text ="ç›®æ¨™:ã•ã£ãé€šã‚Œãªã‹ã£ãŸç™½ã„æŸµã®å‘ã“ã†ã‚’æ¢ç´¢ã—ã‚ˆã†";
        if(storykaunnto==15)mokuhyou.text ="ç›®æ¨™:1Fã¨3Fã‚’æ¢ç´¢ã—ã¦2Fã®éƒ¨å±‹ã®éµã‚’æ‰‹ã«å…¥ã‚Œã¦2Fã®éƒ¨å±‹ã«å…¥ã‚ã†";
        if(storykaunnto==19)mokuhyou.text ="ç›®æ¨™:é«™å¡šã®éƒ¨å±‹ã«å…¥ã‚Šä¸­ã‚’æ¢ç´¢ã—ã‚ˆã†";
        if(storykaunnto==25)mokuhyou.text ="ç›®æ¨™:ç ”ç©¶å®¤ã«å‘ã‹ãŠã†";
        if(storykaunnto==27)mokuhyou.text ="ç›®æ¨™:èµ¤è‰²ã®çµ¨æ¯¯ã®ä¸Šã«è¡Œã“ã†";
        if(storykaunnto==11)tatakai.tatakai1();
        if(storykaunnto==17)
        {
            tatakai.tatakai1();
            tatakai.tusimaba();
        }
        if(storykaunnto==23)
        {
            tatakai.tatakai1();
            tatakai.takatu();
        }

    }
    
        void OnCollisionEnter(Collision collision)
        {
         if  (collision.gameObject.CompareTag("ITEM"))//ITEMã‚²ãƒƒãƒˆã§ãã‚‹ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã«ã¶ã¤ã‹ã£ãŸã‚‰
         {
            if(collision.gameObject.name == "morita_kagi1"&&storykaunnto==15)
            {
                item.name1="2Fã®éƒ¨å±‹éµ1ã¤ç›®";//ã‚¢ã‚¤ãƒ†ãƒ å
                item.item1_get();//ã‚¢ã‚¤ãƒ†ãƒ æ¬„ã®ã©ã®å ´æ‰€ã«ã‚¢ã‚¤ãƒ†ãƒ è¡¨ç¤ºã•ã›ãŸã„ã‹ï¼Ÿ
            }
            if(collision.gameObject.name == "takara"&&storykaunnto==15)
            {
                item.name2="å®ç®±ã®éµ";//ã‚¢ã‚¤ãƒ†ãƒ å
                item.item2_get();//ã‚¢ã‚¤ãƒ†ãƒ æ¬„ã®ã©ã®å ´æ‰€ã«ã‚¢ã‚¤ãƒ†ãƒ è¡¨ç¤ºã•ã›ãŸã„ã‹ï¼Ÿ
            }
            if(collision.gameObject.name == "morita_kagi2"&&storykaunnto==15)
            {
                item.name2="2Fã®éƒ¨å±‹éµ2ã¤ç›®";//ã‚¢ã‚¤ãƒ†ãƒ å
                item.item2_get();//ã‚¢ã‚¤ãƒ†ãƒ æ¬„ã®ã©ã®å ´æ‰€ã«ã‚¢ã‚¤ãƒ†ãƒ è¡¨ç¤ºã•ã›ãŸã„ã‹ï¼Ÿ
            }
             if(collision.gameObject.name == "2FKey"&&storykaunnto==15)
            {
                item.name3="2Fã®éƒ¨å±‹éµ3ã¤ç›®";//ã‚¢ã‚¤ãƒ†ãƒ å
                item.item3_get();//ã‚¢ã‚¤ãƒ†ãƒ æ¬„ã®ã©ã®å ´æ‰€ã«ã‚¢ã‚¤ãƒ†ãƒ è¡¨ç¤ºã•ã›ãŸã„ã‹ï¼Ÿ
            }
            if(collision.gameObject.name == "KeyKey"&&storykaunnto==19)
            {
                item.name3="é«™å¡šã®éƒ¨å±‹ã®éµ";//ã‚¢ã‚¤ãƒ†ãƒ å
                item.item3_get();//ã‚¢ã‚¤ãƒ†ãƒ æ¬„ã®ã©ã®å ´æ‰€ã«ã‚¢ã‚¤ãƒ†ãƒ è¡¨ç¤ºã•ã›ãŸã„ã‹ï¼Ÿ
            }
            if(collision.gameObject.name == "morita_kagi3"&&storykaunnto==25)
            {
                item.name3="é«™å¡šã®ç ”ç©¶å®¤ã®éµ";//ã‚¢ã‚¤ãƒ†ãƒ å
                item.item3_get();//ã‚¢ã‚¤ãƒ†ãƒ æ¬„ã®ã©ã®å ´æ‰€ã«ã‚¢ã‚¤ãƒ†ãƒ è¡¨ç¤ºã•ã›ãŸã„ã‹ï¼Ÿ
            }

         }

         
         if  (collision.gameObject.CompareTag("heya1"))//ã„ã¤ã‚¹ãƒˆãƒ¼ãƒªãƒ¼é€²ã‚ã¦ã‚»ãƒªãƒ•å‡ºã™ã‹
        {
          if(collision.gameObject.name == "heya1"&&storykaunnto==1)
          {
            serihuokuru=1;//Qã‚­ãƒ¼ã‚’æŠ¼ã•ãªãã¦ã‚‚è‡ªå‹•ã§ã‚»ãƒªãƒ•ã‚„æ–‡ç« ã‚’æµã—ãŸã„æ™‚ã¯ä»˜ã‘ã‚‹
            storykaunnto=2;//ã‚¹ãƒˆãƒ¼ãƒªãƒ¼é€²ã‚ã‚‹
          }
         if(collision.gameObject.name == "nazotokitokeru"&&storykaunnto==5)
          {
            serihuokuru=1;//Qã‚­ãƒ¼ã‚’æŠ¼ã•ãªãã¦ã‚‚è‡ªå‹•ã§ã‚»ãƒªãƒ•ã‚„æ–‡ç« ã‚’æµã—ãŸã„æ™‚ã¯ä»˜ã‘ã‚‹
            storykaunnto=6;//ã‚¹ãƒˆãƒ¼ãƒªãƒ¼é€²ã‚ã‚‹
            syuzinnkou.transform.rotation = Quaternion.Euler(0f,-90f,0f);//ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®åº§æ¨™å¤‰æ›´
          }
          if(collision.gameObject.name == "madatoorenai"&&storykaunnto==7)
           {
            susumiseigyo=1;//ã‚¹ãƒˆãƒ¼ãƒªãƒ¼é€²ã‚ãªã„ã¨ãã«ç€ã‘ã‚‹
            serihuokuru=1;//Qã‚­ãƒ¼ã‚’æŠ¼ã•ãªãã¦ã‚‚è‡ªå‹•ã§ã‚»ãƒªãƒ•ã‚„æ–‡ç« ã‚’æµã—ãŸã„æ™‚ã¯ä»˜ã‘ã‚‹
            serihu2.k=1;
            syuzinnkou.transform.position-=transform.forward;
           }

          if(collision.gameObject.name == "tobiraakanai"&&storykaunnto==7)
          {
            syuzinnkou.transform.rotation = Quaternion.Euler(0f,90f,0f);//ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®åº§æ¨™å¤‰æ›´
            serihuokuru=1;//Qã‚­ãƒ¼ã‚’æŠ¼ã•ãªãã¦ã‚‚è‡ªå‹•ã§ã‚»ãƒªãƒ•ã‚„æ–‡ç« ã‚’æµã—ãŸã„æ™‚ã¯ä»˜ã‘ã‚‹
            storykaunnto=8;//ã‚¹ãƒˆãƒ¼ãƒªãƒ¼é€²ã‚ã‚‹
          }
           if(collision.gameObject.name == "moritakennkyuusya"&&storykaunnto==9)
           {
                syuzinnkou.transform.rotation = Quaternion.Euler(0f,-90f,0f);//ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®åº§æ¨™å¤‰æ›´
                serihuokuru=1;//Qã‚­ãƒ¼ã‚’æŠ¼ã•ãªãã¦ã‚‚è‡ªå‹•ã§ã‚»ãƒªãƒ•ã‚„æ–‡ç« ã‚’æµã—ãŸã„æ™‚ã¯ä»˜ã‘ã‚‹
                storykaunnto=10;//ã‚¹ãƒˆãƒ¼ãƒªãƒ¼é€²ã‚ã‚‹
           }

            if(collision.gameObject.name == "akanai"&&storykaunnto==19)
          {
            serihuokuru=1;//Qã‚­ãƒ¼ã‚’æŠ¼ã•ãªãã¦ã‚‚è‡ªå‹•ã§ã‚»ãƒªãƒ•ã‚„æ–‡ç« ã‚’æµã—ãŸã„æ™‚ã¯ä»˜ã‘ã‚‹
            storykaunnto=20;//ã‚¹ãƒˆãƒ¼ãƒªãƒ¼é€²ã‚ã‚‹
          }
        if(collision.gameObject.name == "saigonotatakai"&&storykaunnto==21)
          {
            serihuokuru=1;//Qã‚­ãƒ¼ã‚’æŠ¼ã•ãªãã¦ã‚‚è‡ªå‹•ã§ã‚»ãƒªãƒ•ã‚„æ–‡ç« ã‚’æµã—ãŸã„æ™‚ã¯ä»˜ã‘ã‚‹
            storykaunnto=22;//ã‚¹ãƒˆãƒ¼ãƒªãƒ¼é€²ã‚ã‚‹
            syuzinnkou.transform.rotation = Quaternion.Euler(0f,-90f,0f);//ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®åº§æ¨™å¤‰æ›´
          }
            if(collision.gameObject.name == "honntonisaigo"&&storykaunnto==25)
          {
            serihuokuru=1;//Qã‚­ãƒ¼ã‚’æŠ¼ã•ãªãã¦ã‚‚è‡ªå‹•ã§ã‚»ãƒªãƒ•ã‚„æ–‡ç« ã‚’æµã—ãŸã„æ™‚ã¯ä»˜ã‘ã‚‹
            storykaunnto=26;//ã‚¹ãƒˆãƒ¼ãƒªãƒ¼é€²ã‚ã‚‹
            syuzinnkou.transform.rotation = Quaternion.Euler(0f,-90f,0f);//ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®åº§æ¨™å¤‰æ›´
          }
           if(collision.gameObject.name == "gamehe"&&storykaunnto==27)
          {
            gamekirikae.LaunchExternalExe();
            //UnityEditor.EditorApplication.isPlaying = false;//UNITYã‚¨ãƒ‡ã‚£ã‚¿ä¸Šã§ã‚‚æ­¢ã¾ã‚‹ã‚ˆã†ã«ã™ã‚‹ãŸã‚
            
            

          }

          if(collision.gameObject.name == "moritabatoru"&&storykaunnto==13)
          {
            syuzinnkou.transform.rotation = Quaternion.Euler(0f,90f,0f);//ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®åº§æ¨™å¤‰æ›´
            serihuokuru=1;//Qã‚­ãƒ¼ã‚’æŠ¼ã•ãªãã¦ã‚‚è‡ªå‹•ã§ã‚»ãƒªãƒ•ã‚„æ–‡ç« ã‚’æµã—ãŸã„æ™‚ã¯ä»˜ã‘ã‚‹
            storykaunnto=14;//ã‚¹ãƒˆãƒ¼ãƒªãƒ¼é€²ã‚ã‚‹
          }
            if(collision.gameObject.name == "tusima"&&storykaunnto==15)
          {
            syuzinnkou.transform.rotation = Quaternion.Euler(0f,0f,0f);//ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®åº§æ¨™å¤‰æ›´
            serihuokuru=1;//Qã‚­ãƒ¼ã‚’æŠ¼ã•ãªãã¦ã‚‚è‡ªå‹•ã§ã‚»ãƒªãƒ•ã‚„æ–‡ç« ã‚’æµã—ãŸã„æ™‚ã¯ä»˜ã‘ã‚‹
            storykaunnto=16;//ã‚¹ãƒˆãƒ¼ãƒªãƒ¼é€²ã‚ã‚‹
          }
          
          if(collision.gameObject.name == "moritagousuto_1doamae"&&storykaunnto==15)move.move_onoff[1]=1;
          if(collision.gameObject.name == "takaramae"&&storykaunnto==15)move.move_onoff[1]=2;
          if(collision.gameObject.name == "moritagousuto_2doamae"&&storykaunnto==15)move.move_onoff[1]=3;
          if(collision.gameObject.name == "2FKeymae"&&storykaunnto==15)move.move_onoff[1]=4;
          if(collision.gameObject.name == "saigoKeymae"&&storykaunnto==19)move.move_onoff[1]=5;
          collision.gameObject.CompareTag("heya1");
          //serihu2.siraberu=1;ğŸ‘ˆQã‚­ãƒ¼ã§èª¿ã¹ã‚‹ã¨ãç”¨
          //siraberu.gameObject.SetActive(!siraberu.gameObject.activeSelf);ğŸ‘ˆQã‚­ãƒ¼ã§èª¿ã¹ã‚‹ã¨ãç”¨
        }
         if(collision.gameObject.CompareTag("2_pass"))//ã„ã¤ã‚¹ãƒˆãƒ¼ãƒªãƒ¼é€²ã‚ã¦ã‚»ãƒªãƒ•å‡ºã™ã‹
        {
          if(storykaunnto==3)
          {
            susumiseigyo=1;//ã‚¹ãƒˆãƒ¼ãƒªãƒ¼é€²ã‚ãªã„ã¨ãã«ç€ã‘ã‚‹
            if (collision.gameObject.name == "irigutipas") serihu2.siraberu=1;//ğŸ‘ˆQã‚­ãƒ¼ã§èª¿ã¹ã‚‹ã¨ãç”¨ã€ã¨ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®åå‰ã‹ã‚‰ã‚¢ãƒ‰ãƒ¬ã‚¹ã®æŒ‡å®šã€
            if (collision.gameObject.name == "irigutipas2") serihu2.siraberu=2;//ğŸ‘ˆQã‚­ãƒ¼ã§èª¿ã¹ã‚‹ã¨ãç”¨ã€ã¨ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®åå‰ã‹ã‚‰ã‚¢ãƒ‰ãƒ¬ã‚¹ã®æŒ‡å®šã€
            if (collision.gameObject.name == "irigutipas3") serihu2.siraberu=3;//ğŸ‘ˆQã‚­ãƒ¼ã§èª¿ã¹ã‚‹ã¨ãç”¨ã€ã¨ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®åå‰ã‹ã‚‰ã‚¢ãƒ‰ãƒ¬ã‚¹ã®æŒ‡å®šã€
            collision.gameObject.CompareTag("2_pass");
            siraberu.gameObject.SetActive(!siraberu.gameObject.activeSelf);//ğŸ‘ˆQã‚­ãƒ¼ã§èª¿ã¹ã‚‹ã¨ãç”¨
          }
          if(storykaunnto==7)
          {
            susumiseigyo=1;//ã‚¹ãƒˆãƒ¼ãƒªãƒ¼é€²ã‚ãªã„ã¨ãã«ç€ã‘ã‚‹
            if (collision.gameObject.name == "pas1") serihu2.siraberu=1;//ğŸ‘ˆQã‚­ãƒ¼ã§èª¿ã¹ã‚‹ã¨ãç”¨ã€ã¨ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®åå‰ã‹ã‚‰ã‚¢ãƒ‰ãƒ¬ã‚¹ã®æŒ‡å®šã€
            collision.gameObject.CompareTag("2_pass");
            siraberu.gameObject.SetActive(!siraberu.gameObject.activeSelf);//ğŸ‘ˆQã‚­ãƒ¼ã§èª¿ã¹ã‚‹ã¨ãç”¨
          }
          if(storykaunnto==21)
          {
             susumiseigyo=1;//ã‚¹ãƒˆãƒ¼ãƒªãƒ¼é€²ã‚ãªã„ã¨ãã«ç€ã‘ã‚‹
             if (collision.gameObject.name == "") serihu2.siraberu=1;//ğŸ‘ˆQã‚­ãƒ¼ã§èª¿ã¹ã‚‹ã¨ãç”¨ã€ã¨ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®åå‰ã‹ã‚‰ã‚¢ãƒ‰ãƒ¬ã‚¹ã®æŒ‡å®šã€
            collision.gameObject.CompareTag("2_pass");
            siraberu.gameObject.SetActive(!siraberu.gameObject.activeSelf);//ğŸ‘ˆQã‚­ãƒ¼ã§èª¿ã¹ã‚‹ã¨ãç”¨
          }
        }
             if(collision.gameObject.name == "erebeitaa1"&&(storykaunnto==15||storykaunnto==19))
        {
            move.move_onoff[2]=1;
            move.move_onoff[4]=0;
            e.erebeita();
            move.arukanai=1;
            move.main.enabled=false;
            syuzinnkou.transform.position=move.moritaF1;
            
        }
        if(collision.gameObject.name == "erebeitaa2"&&(storykaunnto==15||storykaunnto==19))
        {
            move.move_onoff[2]=2;
             move.move_onoff[4]=0;
            e.erebeita();
            move.arukanai=1;
             move.main.enabled=false;
            syuzinnkou.transform.position=move.moritaF2;
        }
        if(collision.gameObject.name == "erebeitaa3"&&(storykaunnto==15||storykaunnto==19))
        {
            move.move_onoff[2]=3;
             move.move_onoff[4]=0;
            e.erebeita();
            move.arukanai=1;
            move.main.enabled=false;
            syuzinnkou.transform.position=move.moritaF3;
        }
        if(collision.gameObject.name == "ere_tukeru"&&(storykaunnto==15||storykaunnto==19))
        {
           
            e.erebeta1.SetActive(true);
            e.erebeta2.SetActive(true);
            e.erebeta3.SetActive(true);
            if( move.move_onoff[7]==0)
            {
                move.move_onoff[7]=1;
                sound.erebetasimaru1();
            }
            move.hiraku_1F.SetActive(true);
            move.hiraku_2F.SetActive(true);
            move.hiraku_3F.SetActive(true);
           
        }

      
        }
     private void OnCollisionExit(Collision collision)//é›¢ã‚ŒãŸã¨ãã«åå¿œã™ã‚‹é–¢æ•°
     {
           if(collision.gameObject.name == "madatoorenai"&&storykaunnto==7)
           {
            serihu2.k=0;
           }

     if (collision.gameObject.CompareTag("2_pass"))
        {
            serihu2.siraberu=0;//é›¢ã‚ŒãŸã‚‰èª¿ã¹ã‚‰ã‚Œãªã„ã‚ˆã†ã«ã™ã‚‹(âš ä¼šè©±ä¸­ã«èª¿ã¹ã¦ã„ã‚‹ç‰©ä½“ã‹ã‚‰é›¢ã‚ŒãŸã‚‰ãƒã‚°ã‚‹)
            Debug.Log("ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰ã¨é›¢ã‚Œã¾ã—ãŸ");
            siraberu.gameObject.SetActive(!siraberu.gameObject.activeSelf);
        }
 if((collision.gameObject.name == "2FKeymae"||collision.gameObject.name == "moritagousuto_2doamae"||collision.gameObject.name == "takaramae"||collision.gameObject.name == "moritagousuto_1doamae")&&(storykaunnto==15||storykaunnto==19))move.move_onoff[1]=0;

     }
     
}
